
	tr_sulfur = {
		["name"] = "Sulfur",
		["desc"] = "Used to create Gunpowder",
		["model"] = "models/props_wasteland/prison_toiletchunk01f.mdl",
		["weight"] = 0.01,
		["notrade"] = false,
		["tradeskill"] = true,
		["unique"] = false,
		["quest"] = false,
		["amount"] = 1,
		["buy_high"] = 1,
		["buy_low"] = 1,
		["chance"] = 50
	}
	tr_sulfur_rare = {
		["name"] = "Sulfur",
		["desc"] = "Used to create Gunpowder",
		["model"] = "models/props_wasteland/prison_toiletchunk01f.mdl",
		["weight"] = 0.01,
		["notrade"] = false,
		["tradeskill"] = true,
		["unique"] = false,
		["quest"] = false,
		["amount"] = 1,
		["buy_high"] = 1,
		["buy_low"] = 1,
		["chance"] = 10
	}
	tr_metalfrags = {
		["name"] = "Metal Fragments",
		["desc"] = "Used in various tradeskills",
		["model"] = "models/props_c17/canisterchunk01i.mdl",
		["weight"] = 0.1,
		["notrade"] = false,
		["tradeskill"] = true,
		["unique"] = false,
		["quest"] = false,
		["amount"] = 1,
		["buy_high"] = 3,
		["buy_low"] = 2,
		["chance"] = 20
	}
	tr_drugs = {
		["name"] = "Unidentified Drugs",
		["desc"] = "models/props_lab/jar01b.mdl",
		["model"] = "",
		["weight"] = 1,
		["notrade"] = false,
		["tradeskill"] = true,
		["unique"] = false,
		["quest"] = false,
		["amount"] = 1,
		["buy_high"] = 1,
		["buy_low"] = 1,
		["chance"] = 5
	}
	tr_cmeat = {
		["name"] = "Headcrab Meat",
		["desc"] = "Meat from a Headcrab",
		["model"] = "models/gibs/antlion_gib_small_2.mdl",
		["weight"] = 1,
		["notrade"] = false,
		["tradeskill"] = true,
		["unique"] = false,
		["quest"] = false,
		["amount"] = 1,
		["buy_high"] = 1,
		["buy_low"] = 1,
		["chance"] = 20
	}
	tr_zmeat = {
		["name"] = "Zombie Meat",
		["desc"] = "Rotting Meat from a Zombie",
		["model"] = "models/gibs/antlion_gib_small_3.mdl",
		["weight"] = 1,
		["notrade"] = false,
		["tradeskill"] = true,
		["unique"] = false,
		["quest"] = false,
		["amount"] = 1,
		["buy_high"] = 1,
		["buy_low"] = 1,
		["chance"] = 25
	}
	tr_ameat = {
		["name"] = "Antlion Meat",
		["desc"] = "Prime Meat from an Antlion",
		["model"] = "models/gibs/antlion_gib_medium_2.mdl",
		["weight"] = 1,
		["notrade"] = false,
		["tradeskill"] = true,
		["unique"] = false,
		["quest"] = false,
		["amount"] = 1,
		["buy_high"] = 1,
		["buy_low"] = 1,
		["chance"] = 15
	}